export default {
  bgMainColor: "#FFFFFF",
  bgSubColor: "#1F1F25",
  bgPopColor: "#FFFFFF",
  bgLineColor: "#FFFFFF",
  borderMainColor: "#d7d7d7",
  fontMainColor: "#1F1F25",
  fontSubColor: "#EFEFF0",
  fontPopColor: "#595967",
  highlightColor: "#A1C950",
  lineMainColor: "#1F1F25",
  lineSubColor: "#808080",
  bgFooterColor: "#0F0F12",
  fontFooterColor: "#FFFFFF",
};
